In [1]:
import numpy as np
import pickle as pk
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist
from tensorflow import keras
from sklearn import metrics
# from tensorflow.keras.utils import np_utils

In [2]:
(train_x, train_y), (test_x, test_y) = fashion_mnist.load_data()

In [3]:
# Printing dimensions
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


num_features = 784
num_classes = 10

# Reshaping the tensor into (,784)
train_x = train_x.reshape([train_x.shape[0], 28, 28, 1]).astype('float32')
test_x = test_x.reshape([test_x.shape[0], 28, 28, 1]).astype('float32')

train_y = tf.keras.utils.to_categorical(train_y)
y_test_orig = test_y
test_y = tf.keras.utils.to_categorical(test_y)

# Printing dimensions
print("\nAfter Reshaping")
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


# Normalizing
train_x = train_x/255
test_x = test_x/255

Training Set:
train_x shape:  (60000, 28, 28)
train_y shape:  (60000,)
Test Set:
test_x shape:  (10000, 28, 28)
test_y shape:  (10000,)

After Reshaping
Training Set:
train_x shape:  (60000, 28, 28, 1)
train_y shape:  (60000, 10)
Test Set:
test_x shape:  (10000, 28, 28, 1)
test_y shape:  (10000, 10)


In [8]:
# Building the model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), input_shape=(28, 28, 1), activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))
model.add(tf.keras.layers.Conv2D(filters=64, kernel_size=(3,3), activation='relu', padding='same'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(256, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 28, 28, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 14, 14, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 7, 7, 64)          0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 7, 7, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 3136)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 256)              

In [10]:
model.fit(x=train_x, y=train_y, verbose=1, batch_size=64, epochs=35, validation_data=(test_x, test_y))

Epoch 1/35
938/938 [==============================] - 60s 63ms/step - loss: 0.3292 - accuracy: 0.8813 - val_loss: 0.2877 - val_accuracy: 0.8957
Epoch 2/35
938/938 [==============================] - 58s 62ms/step - loss: 0.2626 - accuracy: 0.9032 - val_loss: 0.2870 - val_accuracy: 0.8956
Epoch 3/35
938/938 [==============================] - 59s 63ms/step - loss: 0.2280 - accuracy: 0.9158 - val_loss: 0.2462 - val_accuracy: 0.9088
Epoch 4/35
938/938 [==============================] - 61s 65ms/step - loss: 0.1979 - accuracy: 0.9268 - val_loss: 0.2376 - val_accuracy: 0.9128
Epoch 5/35
938/938 [==============================] - 60s 64ms/step - loss: 0.1784 - accuracy: 0.9340 - val_loss: 0.2360 - val_accuracy: 0.9127
Epoch 6/35
938/938 [==============================] - 61s 65ms/step - loss: 0.1574 - accuracy: 0.9411 - val_loss: 0.2290 - val_accuracy: 0.9195
Epoch 7/35
938/938 [==============================] - 61s 65ms/step - loss: 0.1397 - accuracy: 0.9482 - val_loss: 0.2288 - val_accuracy:

In [6]:
prediction = model.predict(test_x)

predictions = np.argmax(prediction, axis=1)
print(predictions)

[9 2 1 ... 8 1 5]


In [7]:
# Printing the evaluation metrics 
print("Accuracy Score: ")
print(metrics.accuracy_score(y_test_orig, predictions, normalize=True))
print("\nClassification Report: ")
print(metrics.classification_report(y_test_orig, predictions))
print("\nConfusion Matrix: ")
print(metrics.confusion_matrix(y_test_orig, predictions))

Accuracy Score: 
0.9203

Classification Report: 
              precision    recall  f1-score   support

           0       0.87      0.85      0.86      1000
           1       0.99      0.99      0.99      1000
           2       0.86      0.89      0.87      1000
           3       0.93      0.94      0.93      1000
           4       0.88      0.85      0.87      1000
           5       0.99      0.99      0.99      1000
           6       0.77      0.77      0.77      1000
           7       0.95      0.98      0.97      1000
           8       0.98      0.98      0.98      1000
           9       0.98      0.96      0.97      1000

    accuracy                           0.92     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.92      0.92      0.92     10000


Confusion Matrix: 
[[854   0  11  10   4   1 112   0   8   0]
 [  0 987   0   9   1   0   2   0   1   0]
 [ 20   1 894   7  33   0  43   0   2   0]
 [ 11   2  10 935  22   0  19   0   1   0]
