In [1]:
import numpy as np
import pickle as pk
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from sklearn import metrics
# from tensorflow.keras.utils import np_utils

In [2]:
(train_x, train_y), (test_x, test_y) = mnist.load_data()

In [4]:
# Printing dimensions
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


num_features = 784
num_classes = 10

# Reshaping the tensor into (,784)
train_x = train_x.reshape([train_x.shape[0], 28, 28, 1]).astype('float32')
test_x = test_x.reshape([test_x.shape[0], 28, 28, 1]).astype('float32')

train_y = tf.keras.utils.to_categorical(train_y)
y_test_orig = test_y
test_y = tf.keras.utils.to_categorical(test_y)

# Printing dimensions
print("\nAfter Reshaping")
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


# Normalizing
train_x = train_x/255
test_x = test_x/255

Training Set:
train_x shape:  (60000, 28, 28, 1)
train_y shape:  (60000,)
Test Set:
test_x shape:  (10000, 28, 28)
test_y shape:  (10000,)

After Reshaping
Training Set:
train_x shape:  (60000, 28, 28, 1)
train_y shape:  (60000, 10)
Test Set:
test_x shape:  (10000, 28, 28, 1)
test_y shape:  (10000, 10)


In [9]:
# Building the model
model = tf.keras.Sequential()
model.add(tf.keras.layers.Conv2D(filters=32, kernel_size=(3,3), input_shape=(28, 28, 1), activation='relu'))
model.add(tf.keras.layers.MaxPool2D(pool_size=(2,2)))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(128, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 13, 13, 32)        0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 5408)              0         
_________________________________________________________________
dense_2 (Dense)              (None, 128)               692352    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 693,962
Trainable params: 693,962
Non-trainable params: 0
________________________________________________

In [10]:
model.fit(x=train_x, y=train_y, verbose=1, batch_size=200, epochs=25, validation_data=(test_x, test_y))

Epoch 1/25
300/300 [==============================] - 24s 78ms/step - loss: 0.5081 - accuracy: 0.8622 - val_loss: 0.0983 - val_accuracy: 0.9725
Epoch 2/25
300/300 [==============================] - 24s 81ms/step - loss: 0.0966 - accuracy: 0.9728 - val_loss: 0.0616 - val_accuracy: 0.9807
Epoch 3/25
300/300 [==============================] - 25s 83ms/step - loss: 0.0616 - accuracy: 0.9819 - val_loss: 0.0493 - val_accuracy: 0.9843
Epoch 4/25
300/300 [==============================] - 25s 82ms/step - loss: 0.0451 - accuracy: 0.9866 - val_loss: 0.0464 - val_accuracy: 0.9845
Epoch 5/25
300/300 [==============================] - 25s 82ms/step - loss: 0.0370 - accuracy: 0.9894 - val_loss: 0.0436 - val_accuracy: 0.9850
Epoch 6/25
300/300 [==============================] - 25s 83ms/step - loss: 0.0349 - accuracy: 0.9897 - val_loss: 0.0383 - val_accuracy: 0.9865
Epoch 7/25
300/300 [==============================] - 27s 91ms/step - loss: 0.0260 - accuracy: 0.9921 - val_loss: 0.0464 - val_accuracy:

In [11]:
prediction = model.predict(test_x)

predictions = np.argmax(prediction, axis=1)
print(predictions)

[7 2 1 ... 4 5 6]


In [12]:
# Printing the evaluation metrics 
print("Accuracy Score: ")
print(metrics.accuracy_score(y_test_orig, predictions, normalize=True))
print("\nClassification Report: ")
print(metrics.classification_report(y_test_orig, predictions))
print("\nConfusion Matrix: ")
print(metrics.confusion_matrix(y_test_orig, predictions))

Accuracy Score: 
0.9874

Classification Report: 
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.98      0.99      1032
           3       0.97      1.00      0.98      1010
           4       0.98      1.00      0.99       982
           5       0.99      0.98      0.99       892
           6       0.99      0.99      0.99       958
           7       0.98      0.99      0.99      1028
           8       0.99      0.98      0.99       974
           9       0.99      0.96      0.98      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000


Confusion Matrix: 
[[ 974    0    1    0    0    0    2    1    2    0]
 [   0 1127    2    0    1    0    2    1    2    0]
 [   2    3 1016    2    1    0    0    7    1    0]
 [   0    0  