In [15]:
import numpy as np
import pickle as pk
import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow import keras
from sklearn import metrics
# from tensorflow.keras.utils import np_utils

In [9]:
(train_x, train_y), (test_x, test_y) = mnist.load_data()

In [10]:
# Printing dimensions
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


num_features = 784
num_classes = 10

# Reshaping the tensor into (,784)
train_x = train_x.reshape([-1, num_features]).astype('float32')
test_x = test_x.reshape([-1, num_features]).astype('float32')

train_y = tf.keras.utils.to_categorical(train_y)
y_test_orig = test_y
test_y = tf.keras.utils.to_categorical(test_y)

# Printing dimensions
print("\nAfter Reshaping")
print("Training Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


# Normalizing
train_x = train_x/255
test_x = test_x/255

Training Set:
train_x shape:  (60000, 28, 28)
train_y shape:  (60000,)
Test Set:
test_x shape:  (10000, 28, 28)
test_y shape:  (10000,)

After Reshaping
Training Set:
train_x shape:  (60000, 784)
train_y shape:  (60000, 10)
Test Set:
test_x shape:  (10000, 784)
test_y shape:  (10000, 10)


In [11]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(num_features,)))
model.add(tf.keras.layers.Dense(num_features, activation='relu'))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 784)               615440    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                7850      
Total params: 623,290
Trainable params: 623,290
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x=train_x, y=train_y, validation_data=(test_x, test_y),verbose=1, batch_size=200, epochs=12)

Epoch 1/12
300/300 [==============================] - 3s 9ms/step - loss: 0.4843 - accuracy: 0.8627 - val_loss: 0.1479 - val_accuracy: 0.9556
Epoch 2/12
300/300 [==============================] - 2s 8ms/step - loss: 0.1181 - accuracy: 0.9674 - val_loss: 0.0900 - val_accuracy: 0.9718
Epoch 3/12
300/300 [==============================] - 2s 8ms/step - loss: 0.0756 - accuracy: 0.9783 - val_loss: 0.0791 - val_accuracy: 0.9759
Epoch 4/12
300/300 [==============================] - 3s 9ms/step - loss: 0.0502 - accuracy: 0.9859 - val_loss: 0.0707 - val_accuracy: 0.9783
Epoch 5/12
300/300 [==============================] - 4s 12ms/step - loss: 0.0359 - accuracy: 0.9904 - val_loss: 0.0629 - val_accuracy: 0.9800
Epoch 6/12
300/300 [==============================] - 4s 12ms/step - loss: 0.0270 - accuracy: 0.9924 - val_loss: 0.0666 - val_accuracy: 0.9801
Epoch 7/12
300/300 [==============================] - 4s 13ms/step - loss: 0.0187 - accuracy: 0.9953 - val_loss: 0.0601 - val_accuracy: 0.9816
Epo

In [26]:
prediction = model.predict(test_x)

predictions = np.argmax(prediction, axis=1)
print(predictions)

[7 2 1 ... 4 5 6]


In [27]:
# Printing the evaluation metrics 
print("Accuracy Score: ")
print(metrics.accuracy_score(y_test_orig, predictions, normalize=True))
print("\nClassification Report: ")
print(metrics.classification_report(y_test_orig, predictions))
print("\nConfusion Matrix: ")
print(metrics.confusion_matrix(y_test_orig, predictions))

Accuracy Score: 
0.9796

Classification Report: 
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.99      0.99      0.99      1135
           2       0.98      0.97      0.98      1032
           3       0.97      0.99      0.98      1010
           4       0.98      0.98      0.98       982
           5       0.99      0.97      0.98       892
           6       0.99      0.97      0.98       958
           7       0.99      0.97      0.98      1028
           8       0.97      0.98      0.97       974
           9       0.98      0.97      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000


Confusion Matrix: 
[[ 973    1    1    0    0    0    2    1    2    0]
 [   0 1127    2    1    0    0    2    0    3    0]
 [   7    1 1003    3    1    0    2    6    8    1]
 [   0    0  