In [1]:
import numpy as np
import pickle as pk
import sklearn as sk
from sklearn.neural_network import MLPClassifier

In [2]:
train_set, validation_set, test_set = pk.load(open('mnist.pkl', 'rb'), encoding='latin1')

In [3]:
print("Training Set:")
print("Type: ", type(train_set))

print("Validation Set:")
print("Type: ", type(validation_set))

print("Test Set:")
print("Type: ", type(test_set))

Training Set:
Type:  <class 'tuple'>
Validation Set:
Type:  <class 'tuple'>
Test Set:
Type:  <class 'tuple'>


In [4]:
train_x = train_set[0]
train_y = train_set[1]

validation_x = validation_set[0]
validation_y = validation_set[1]

test_x = test_set[0]
test_y = test_set[1]

# Printing dimensions
print("\nTraining Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Validation Set:")
print("validation_x shape: ", test_x.shape)
print("validation_y shape: ", test_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


# Concatenating the Train and Validation sets
train_x = np.concatenate((train_x, validation_x), axis=0)
train_y = np.concatenate((train_y, validation_y), axis=0)


# Printing dimensions
print("\n\nTraining Set:")
print("train_x shape: ", train_x.shape)
print("train_y shape: ", train_y.shape)

print("Test Set:")
print("test_x shape: ", test_x.shape)
print("test_y shape: ", test_y.shape)


# Normalizing
train_x = train_x/255
test_x = test_x/255


Training Set:
train_x shape:  (50000, 784)
train_y shape:  (50000,)
Validation Set:
validation_x shape:  (10000, 784)
validation_y shape:  (10000,)
Test Set:
test_x shape:  (10000, 784)
test_y shape:  (10000,)


Training Set:
train_x shape:  (60000, 784)
train_y shape:  (60000,)
Test Set:
test_x shape:  (10000, 784)
test_y shape:  (10000,)


In [5]:
clf = MLPClassifier(hidden_layer_sizes=500, solver='adam', learning_rate_init=0.01, max_iter=50)
clf.fit(train_x, train_y)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=500, learning_rate_init=0.01, max_iter=50)

In [6]:
predictions = clf.predict(test_x)

In [7]:
# Printing the evaluation metrics 
print("Accuracy Score: ")
print(sk.metrics.accuracy_score(test_y, predictions, normalize=True))
print("\nClassification Report: ")
print(sk.metrics.classification_report(test_y, predictions))
print("\nConfusion Matrix: ")
print(sk.metrics.confusion_matrix(test_y, predictions))

Accuracy Score: 
0.98

Classification Report: 
              precision    recall  f1-score   support

           0       0.98      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.97      0.98      0.98      1032
           3       0.97      0.98      0.97      1010
           4       0.98      0.99      0.98       982
           5       0.99      0.97      0.98       892
           6       0.99      0.97      0.98       958
           7       0.97      0.99      0.98      1028
           8       0.97      0.98      0.98       974
           9       0.99      0.95      0.97      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000


Confusion Matrix: 
[[ 972    0    1    1    0    0    0    1    4    1]
 [   0 1123    3    2    0    1    2    1    3    0]
 [   2    1 1010    3    1    0    0    8    7    0]
 [   0    0    

In [11]:
clf1 = MLPClassifier(hidden_layer_sizes=800, solver='adam', learning_rate_init=0.01, max_iter=50)
clf1.fit(train_x, train_y)

C:\Users\Admin\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:582: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=800, learning_rate_init=0.01, max_iter=50)

In [12]:
predictions1 = clf1.predict(test_x)

In [13]:
# Printing the evaluation metrics 
print("Accuracy Score: ")
print(sk.metrics.accuracy_score(test_y, predictions1, normalize=True))
print("\nClassification Report: ")
print(sk.metrics.classification_report(test_y, predictions1))
print("\nConfusion Matrix: ")
print(sk.metrics.confusion_matrix(test_y, predictions1))

Accuracy Score: 
0.9797

Classification Report: 
              precision    recall  f1-score   support

           0       0.99      0.99      0.99       980
           1       0.99      0.99      0.99      1135
           2       0.99      0.97      0.98      1032
           3       0.98      0.98      0.98      1010
           4       0.96      0.99      0.97       982
           5       0.99      0.97      0.98       892
           6       0.98      0.98      0.98       958
           7       0.98      0.98      0.98      1028
           8       0.96      0.98      0.97       974
           9       0.98      0.97      0.98      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.98      0.98     10000
weighted avg       0.98      0.98      0.98     10000


Confusion Matrix: 
[[ 970    0    1    0    1    0    2    1    4    1]
 [   0 1124    2    2    0    0    2    1    4    0]
 [   4    3 1002    2    7    0    2    6    6    0]
 [   0    0  